base_url = "https://mlsp2025-decoding-brain.github.io/"
compile_sass = true
build_search_index = false
generate_feeds = false
minify_html = true
theme = "academic-workshop"
ignored_static = ["sponsorship_prospectus.pdf","travel-support-CVs/*"]

[markdown]
highlight_code = false
smart_punctuation = true

[extra]
title = {tagline = "Special Session on", title = "Decoding the brain time series", subtitles = ["MLSP 2025 @ Istanbul, Turkey", "August 31-September 3"]}
banner = {extension = "svg", size = "fit-height", fade = true}
header_pages = [{name = "Home", url = "/#home"},{name = "Schedule", url = "/#schedule"}]
